name: Continous Integration

on:
  push:
  workflow_dispatch:

jobs:
  styling:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Check out workspace repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
      # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM development dependencies
        run: npm ci
      - name: Run formatting
        run: npm run format
      - name: Run linting
        run: npm run lint
      - name: Push formatting and linting fixes
      # https://github.com/marketplace/actions/add-commit
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'format: Automatic formatted and linted stuff'
          push: true

  testing:
    needs: styling

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Check out workspace repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
      # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM development dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:ci
      # https://github.com/marketplace/actions/jest-coverage-comment
      - name: Jest coverage comment
        if: ${{ always() }}
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          title: Jest Coverage
          summary-title: jest Summary
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
      - name: Check the output coverage
        run: |
          echo "Summary Report"
          echo "Coverage Percantage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Junit Report"
          echo "tests - ${{ steps.coverageComment.outputs.tests }}"
          echo "skipped - ${{ steps.coverageComment.outputs.skipped }}"
          echo "failures - ${{ steps.coverageComment.outputs.failures }}"
          echo "errors - ${{ steps.coverageComment.outputs.errors }}"
          echo "time - ${{ steps.coverageComment.outputs.time }}"
          echo "Coverage Report"
          echo "lines - ${{ steps.coverageComment.outputs.lines }}"
          echo "branches - ${{ steps.coverageComment.outputs.branches }}"
          echo "functions - ${{ steps.coverageComment.outputs.functions }}"
          echo "statements - ${{ steps.coverageComment.outputs.statements }}"
          echo "coverage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "color - ${{ steps.coverageComment.outputs.color }}"
