name: Continous Integration

on:
  push:
  workflow_dispatch:

jobs:
  styling:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Check out workspace repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
      # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM development dependencies
        run: npm ci
      - name: Run formatting
        run: npm run format
      - name: Run linting
        run: npm run lint
        if: github.event_name != 'pull_request'
      - name: Run linting review
        uses: reviewdog/action-eslint@v1
        if: github.event_name == 'pull_request'
        with:
          reporter: eslint check
          eslint_flags: '--fix'
      - name: Push formatting and linting fixes
      # https://github.com/marketplace/actions/add-commit
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'format: Automatic formatted and linted stuff'
          push: true

  testing:
    needs: styling

    strategy:
      matrix:
        node-version: [15.x, 16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Check out workspace repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
      # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM development dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:ci
      # https://github.com/marketplace/actions/jest-coverage-comment
      - name: Jest coverage comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-summary.json